In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({'Text':['Learnbay teaches NLP',
                        'NLP is in demand in market',
                        'We have to learn NLP']})

In [3]:
df

Text
0        Learnbay teaches NLP
1  NLP is in demand in market
2        We have to learn NLP

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv=CountVectorizer(binary=True)

In [6]:
bow_true=cv.fit_transform(df['Text'])

In [7]:
bow_true.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1]], dtype=int64)

In [8]:
len(cv.vocabulary_)

11

In [9]:
cv.vocabulary_

{'learnbay': 5,
 'teaches': 8,
 'nlp': 7,
 'is': 3,
 'in': 2,
 'demand': 0,
 'market': 6,
 'we': 10,
 'have': 1,
 'to': 9,
 'learn': 4}

In [10]:
cv_1=CountVectorizer(binary=False)

In [11]:
bow_false=cv_1.fit_transform(df['Text'])

In [12]:
bow_false.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 0, 2, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1]], dtype=int64)

In [13]:
df_1=pd.DataFrame({'Text':['This Pasta is Tasty', 
                             'This Pasta is not Tasty',
                          'Pasty is delecious',
                             'I like pasta very much',
                           'Pasta is good but cost is little high',
                             'Pasta tast is good and affordable',
    'Pasta test is really nice however price is not an affordable']})

In [14]:
df_1

Text
0                                This Pasta is Tasty
1                            This Pasta is not Tasty
2                                 Pasty is delecious
3                             I like pasta very much
4              Pasta is good but cost is little high
5                  Pasta tast is good and affordable
6  Pasta test is really nice however price is not...

In [17]:
cv_1_gram=CountVectorizer(ngram_range=(1,1))

In [18]:
bow_uni_gram=cv_1_gram.fit_transform(df_1['Text'])

In [19]:
bow_uni_gram.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1],
       [0, 0, 0, 1, 1, 0, 1, 1, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0],
       [1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 0]], dtype=int64)

In [21]:
print(cv_1_gram.vocabulary_)

{'this': 22, 'pasta': 15, 'is': 9, 'tasty': 20, 'not': 14, 'pasty': 16, 'delecious': 5, 'like': 10, 'very': 23, 'much': 12, 'good': 6, 'but': 3, 'cost': 4, 'little': 11, 'high': 7, 'tast': 19, 'and': 2, 'affordable': 0, 'test': 21, 'really': 18, 'nice': 13, 'however': 8, 'price': 17, 'an': 1}


In [22]:
cv_2_gram=CountVectorizer(ngram_range=(1,2))

In [23]:
bow_bi_gram=cv_2_gram.fit_transform(df_1['Text'])

In [24]:
print(cv_2_gram.vocabulary_)

{'this': 49, 'pasta': 33, 'is': 16, 'tasty': 46, 'this pasta': 50, 'pasta is': 34, 'is tasty': 22, 'not': 30, 'is not': 20, 'not tasty': 32, 'pasty': 38, 'delecious': 9, 'pasty is': 39, 'is delecious': 17, 'like': 23, 'very': 51, 'much': 27, 'like pasta': 24, 'pasta very': 37, 'very much': 52, 'good': 10, 'but': 5, 'cost': 7, 'little': 25, 'high': 13, 'is good': 18, 'good but': 12, 'but cost': 6, 'cost is': 8, 'is little': 19, 'little high': 26, 'tast': 44, 'and': 3, 'affordable': 0, 'pasta tast': 35, 'tast is': 45, 'good and': 11, 'and affordable': 4, 'test': 47, 'really': 42, 'nice': 28, 'however': 14, 'price': 40, 'an': 1, 'pasta test': 36, 'test is': 48, 'is really': 21, 'really nice': 43, 'nice however': 29, 'however price': 15, 'price is': 41, 'not an': 31, 'an affordable': 2}


In [25]:
bow_bi_gram.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
      

In [26]:
cv_2_2_gram=CountVectorizer(ngram_range=(2,2))

In [27]:
bow_2_2_gram=cv_2_2_gram.fit_transform(df_1['Text'])

In [28]:
print(cv_2_2_gram.vocabulary_)

{'this pasta': 27, 'pasta is': 18, 'is tasty': 12, 'is not': 10, 'not tasty': 17, 'pasty is': 22, 'is delecious': 7, 'like pasta': 13, 'pasta very': 21, 'very much': 28, 'is good': 8, 'good but': 5, 'but cost': 2, 'cost is': 3, 'is little': 9, 'little high': 14, 'pasta tast': 19, 'tast is': 25, 'good and': 4, 'and affordable': 1, 'pasta test': 20, 'test is': 26, 'is really': 11, 'really nice': 24, 'nice however': 15, 'however price': 6, 'price is': 23, 'not an': 16, 'an affordable': 0}


In [29]:
cv_3_gram=CountVectorizer(ngram_range=(1,3))

In [30]:
bow_3_gram=cv_3_gram.fit_transform(df_1['Text'])

In [31]:
print(cv_3_gram.vocabulary_)

{'this': 74, 'pasta': 47, 'is': 21, 'tasty': 70, 'this pasta': 75, 'pasta is': 48, 'is tasty': 33, 'this pasta is': 76, 'pasta is tasty': 51, 'not': 43, 'is not': 28, 'not tasty': 46, 'pasta is not': 50, 'is not tasty': 30, 'pasty': 58, 'delecious': 11, 'pasty is': 59, 'is delecious': 22, 'pasty is delecious': 60, 'like': 34, 'very': 77, 'much': 39, 'like pasta': 35, 'pasta very': 56, 'very much': 78, 'like pasta very': 36, 'pasta very much': 57, 'good': 12, 'but': 5, 'cost': 8, 'little': 37, 'high': 17, 'is good': 23, 'good but': 15, 'but cost': 6, 'cost is': 9, 'is little': 26, 'little high': 38, 'pasta is good': 49, 'is good but': 25, 'good but cost': 16, 'but cost is': 7, 'cost is little': 10, 'is little high': 27, 'tast': 67, 'and': 3, 'affordable': 0, 'pasta tast': 52, 'tast is': 68, 'good and': 13, 'and affordable': 4, 'pasta tast is': 53, 'tast is good': 69, 'is good and': 24, 'good and affordable': 14, 'test': 71, 'really': 64, 'nice': 40, 'however': 18, 'price': 61, 'an': 1, 

In [32]:
cv_3_3_gram=CountVectorizer(ngram_range=(3,3))

In [33]:
bow_3_gram=cv_3_3_gram.fit_transform(df_1['Text'])

In [34]:
print(cv_3_3_gram.vocabulary_)

{'this pasta is': 25, 'pasta is tasty': 16, 'pasta is not': 15, 'is not tasty': 9, 'pasty is delecious': 20, 'like pasta very': 11, 'pasta very much': 19, 'pasta is good': 14, 'is good but': 6, 'good but cost': 3, 'but cost is': 0, 'cost is little': 1, 'is little high': 7, 'pasta tast is': 17, 'tast is good': 23, 'is good and': 5, 'good and affordable': 2, 'pasta test is': 18, 'test is really': 24, 'is really nice': 10, 'really nice however': 22, 'nice however price': 12, 'however price is': 4, 'price is not': 21, 'is not an': 8, 'not an affordable': 13}


In [35]:
bow_3_gram.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 0, 1, 0]], dtype=int64)

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [44]:
tfidf=TfidfVectorizer()

In [45]:
tf=tfidf.fit_transform(df_1['Text'])

In [48]:
tf.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.35120361,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.35120361, 0.        , 0.        , 0.        , 0.        ,
        0.61372308, 0.        , 0.61372308, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.29932725,
        0.        , 0.        , 0.        , 0.        , 0.52306991,
        0.29932725, 0.        , 0.        , 0.        , 0.        ,
        0.52306991, 0.        , 0.52306991, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.67030489, 0.        , 0.        , 0.        , 0.3184065 ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.67030489, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.   

In [53]:
print(tfidf.vocabulary_)

{'this': 22, 'pasta': 15, 'is': 9, 'tasty': 20, 'not': 14, 'pasty': 16, 'delecious': 5, 'like': 10, 'very': 23, 'much': 12, 'good': 6, 'but': 3, 'cost': 4, 'little': 11, 'high': 7, 'tast': 19, 'and': 2, 'affordable': 0, 'test': 21, 'really': 18, 'nice': 13, 'however': 8, 'price': 17, 'an': 1}


In [54]:
tfidf_4_gram=TfidfVectorizer(ngram_range=(1,4))

In [55]:
tf_4=tfidf_4_gram.fit_transform(df_1['Text'])

In [56]:
print(tfidf_4_gram.vocabulary_)

{'this': 92, 'pasta': 57, 'is': 25, 'tasty': 87, 'this pasta': 93, 'pasta is': 58, 'is tasty': 41, 'this pasta is': 94, 'pasta is tasty': 63, 'this pasta is tasty': 96, 'not': 53, 'is not': 34, 'not tasty': 56, 'pasta is not': 61, 'is not tasty': 37, 'this pasta is not': 95, 'pasta is not tasty': 62, 'pasty': 72, 'delecious': 13, 'pasty is': 73, 'is delecious': 26, 'pasty is delecious': 74, 'like': 42, 'very': 97, 'much': 48, 'like pasta': 43, 'pasta very': 70, 'very much': 98, 'like pasta very': 44, 'pasta very much': 71, 'like pasta very much': 45, 'good': 14, 'but': 5, 'cost': 9, 'little': 46, 'high': 20, 'is good': 27, 'good but': 17, 'but cost': 6, 'cost is': 10, 'is little': 32, 'little high': 47, 'pasta is good': 59, 'is good but': 30, 'good but cost': 18, 'but cost is': 7, 'cost is little': 11, 'is little high': 33, 'pasta is good but': 60, 'is good but cost': 31, 'good but cost is': 19, 'but cost is little': 8, 'cost is little high': 12, 'tast': 83, 'and': 3, 'affordable': 0, 

In [57]:
tf_4.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.18336634, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.38602023, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.18336634, 0.27389289, 0.        ,
        0.        , 0.        , 0.        , 0.38602023, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  