In [1]:
from sklearn.datasets import load_digits

In [2]:
digits=load_digits()

In [3]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [4]:
digits['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [5]:
digits['target']

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
import numpy as np
import pandas as pd

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron

In [8]:
x=digits['data']

In [9]:
y=digits['target']

In [12]:
pd.DataFrame(x).shape

(1797, 64)

In [13]:
pd.DataFrame(y).shape

(1797, 1)

In [14]:
pd.DataFrame(y).value_counts()

0
3    183
1    182
5    182
4    181
6    181
9    180
7    179
0    178
2    177
8    174
Name: count, dtype: int64

In [15]:
pd.DataFrame(y).nunique()

0    10
dtype: int64

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1437, 64)
(360, 64)
(1437,)
(360,)


In [18]:
p=Perceptron()

In [19]:
p.fit(x_train,y_train)

Perceptron()

In [21]:
prediction=p.predict(x_test)

In [22]:
prediction

array([6, 9, 3, 7, 2, 1, 5, 2, 5, 2, 1, 4, 4, 0, 4, 2, 3, 7, 8, 8, 4, 3,
       9, 7, 5, 6, 3, 5, 6, 3, 4, 9, 1, 4, 4, 6, 9, 4, 7, 6, 6, 9, 1, 3,
       6, 1, 3, 0, 6, 5, 5, 1, 9, 5, 6, 0, 9, 0, 0, 1, 0, 4, 5, 2, 4, 5,
       7, 0, 7, 5, 9, 5, 5, 4, 7, 0, 4, 5, 5, 9, 9, 0, 2, 3, 8, 0, 6, 4,
       4, 9, 1, 2, 8, 3, 5, 2, 9, 4, 4, 4, 4, 3, 5, 3, 1, 3, 5, 9, 4, 2,
       7, 7, 4, 4, 1, 9, 2, 7, 8, 7, 2, 6, 9, 4, 0, 7, 2, 7, 5, 8, 7, 5,
       7, 9, 0, 6, 6, 4, 2, 8, 0, 9, 4, 6, 9, 9, 6, 9, 0, 5, 5, 6, 6, 0,
       6, 4, 2, 9, 3, 8, 7, 2, 9, 0, 4, 5, 8, 6, 5, 8, 9, 8, 4, 2, 1, 3,
       7, 7, 2, 2, 3, 9, 8, 0, 3, 2, 2, 5, 6, 9, 9, 4, 1, 2, 4, 2, 3, 6,
       4, 8, 5, 9, 5, 7, 8, 9, 4, 8, 1, 5, 4, 4, 9, 6, 1, 8, 6, 0, 4, 5,
       2, 7, 4, 6, 4, 5, 6, 0, 3, 2, 3, 6, 7, 1, 5, 1, 4, 7, 6, 5, 1, 5,
       5, 1, 5, 2, 8, 8, 9, 5, 7, 6, 2, 2, 2, 3, 4, 8, 8, 3, 6, 0, 9, 7,
       7, 0, 1, 0, 4, 5, 1, 5, 3, 6, 0, 4, 1, 0, 0, 3, 6, 5, 9, 7, 3, 5,
       5, 9, 9, 8, 5, 3, 3, 2, 0, 5, 8, 3, 4, 0, 2,

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
accuracy_score(y_test,prediction)

0.9527777777777777

In [25]:
prediction_training=p.predict(x_train)

In [27]:
accuracy_score(y_train,prediction_training)

0.9714683368128044

In [28]:
from sklearn.metrics import classification_report

In [31]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98        33
           1       0.93      1.00      0.97        28
           2       0.94      1.00      0.97        33
           3       1.00      0.91      0.95        34
           4       0.92      1.00      0.96        46
           5       0.92      0.96      0.94        47
           6       0.97      0.97      0.97        35
           7       1.00      0.97      0.99        34
           8       0.89      0.83      0.86        30
           9       0.97      0.90      0.94        40

    accuracy                           0.95       360
   macro avg       0.96      0.95      0.95       360
weighted avg       0.95      0.95      0.95       360



In [32]:
print(classification_report(y_train,prediction_training))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       145
           1       0.92      0.99      0.95       154
           2       0.98      1.00      0.99       144
           3       1.00      0.93      0.97       149
           4       0.99      0.99      0.99       135
           5       0.94      1.00      0.97       135
           6       0.98      1.00      0.99       146
           7       0.99      0.99      0.99       145
           8       0.95      0.87      0.91       144
           9       0.98      0.95      0.96       140

    accuracy                           0.97      1437
   macro avg       0.97      0.97      0.97      1437
weighted avg       0.97      0.97      0.97      1437



Regression

In [34]:
dataset=pd.read_csv('/content/HousingData.csv')

In [35]:
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7  396.90    NaN  36.2

In [41]:
dataset.shape

(506, 14)

In [36]:
dataset.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [37]:
dataset.isnull().sum()/len(dataset)*100

CRIM       3.952569
ZN         3.952569
INDUS      3.952569
CHAS       3.952569
NOX        0.000000
RM         0.000000
AGE        3.952569
DIS        0.000000
RAD        0.000000
TAX        0.000000
PTRATIO    0.000000
B          0.000000
LSTAT      3.952569
MEDV       0.000000
dtype: float64

In [38]:
x=dataset.iloc[:,0:-1]

In [39]:
y=dataset.iloc[:,-1]

In [40]:
x.shape

(506, 13)

In [42]:
y.shape

(506,)

In [43]:
x_train_initial,x_test_initial,y_train_initial,y_test_initial=train_test_split(x,y,test_size=0.2,random_state=42)

In [44]:
print(x_train_initial.shape)
print(x_test_initial.shape)
print(y_train_initial.shape)
print(y_test_initial.shape)

(404, 13)
(102, 13)
(404,)
(102,)


In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
sc=StandardScaler()

In [47]:
x_train_initial_scaled=sc.fit_transform(x_train_initial)

In [48]:
x_test_initial_scaled=sc.transform(x_test_initial)

In [50]:
pd.DataFrame(x_train_initial_scaled)

0         1         2         3   ...        9         10        11        12
0    1.268964 -0.492039  1.053967 -0.278887  ...  1.578434  0.845343 -0.074337  1.753482
1   -0.330454 -0.492039 -0.399877 -0.278887  ... -0.584648  1.204741  0.430184 -0.565618
2   -0.396307       NaN -0.703492 -0.278887  ... -0.602724 -0.637176  0.065297 -0.655899
3    0.383154 -0.492039  1.053967 -0.278887  ...  1.578434  0.845343 -3.868193  1.524957
4   -0.319520 -0.492039 -0.399877 -0.278887  ... -0.584648  1.204741  0.379119 -0.169227
..        ...       ...       ...       ...  ...       ...       ...       ...       ...
399 -0.381137 -0.492039 -0.338571 -0.278887  ... -0.120700  1.159817  0.430731  0.871829
400 -0.366920  0.363201 -0.572120 -0.278887  ... -1.090773  0.126546  0.353970  0.073404
401 -0.398490  2.928920 -1.294663 -0.278887  ... -0.747331 -0.592251  0.379010 -0.915457
402  0.839779 -0.492039  1.053967 -0.278887  ...  1.578434  0.845343 -2.694586  1.522136
403 -0.374742 -0.492039 -0.338571 -0.278887  ... -0.120700  1.159817 -3.121581 -0.260918

[404 rows x 13 columns]

In [51]:
pd.DataFrame(x_test_initial_scaled)

0         1         2         3   ...        9         10        11        12
0   -0.389961 -0.492039       NaN -0.278887  ... -0.650926 -0.771951  0.428872 -0.485211
1   -0.393887  1.218440 -0.652403  3.585686  ... -0.903989 -0.322703  0.444180 -1.262476
2   -0.388410 -0.492039  2.461101 -0.278887  ...  1.849573  0.800418  0.369934  0.788601
3   -0.389976 -0.492039 -0.010142 -0.278887  ... -0.596698  0.396095  0.378682 -0.981758
4    0.165368 -0.492039  1.053967 -0.278887  ...  1.578434  0.845343  0.315043  0.675749
..        ...       ...       ...       ...  ...       ...       ...       ...       ...
97   1.689772 -0.492039  1.053967 -0.278887  ...  1.578434  0.845343 -3.580942  3.087951
98   1.202014 -0.492039  1.053967 -0.278887  ...  1.578434  0.845343 -3.595156  0.785780
99   1.160896 -0.492039  1.053967 -0.278887  ...  1.578434  0.845343 -3.512491  1.232954
100 -0.394394 -0.492039 -0.932662 -0.278887  ... -0.946166  0.081621  0.434230  0.053655
101 -0.389590 -0.492039  0.284714 -0.278887  ... -0.036346  0.171470  0.294705 -0.499317

[102 rows x 13 columns]

In [52]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [53]:
model_without_imputation=Sequential()
model_without_imputation.add(Dense(32,activation='relu',input_dim=13))
model_without_imputation.add(Dense(16,activation='relu'))
model_without_imputation.add(Dense(1,activation='linear'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [54]:
model_without_imputation.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │             448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 993 (3.88 KB)

 Trainable params: 993 (3.88 KB)

 Non-trainable params: 0 (0.00 B)

In [55]:
model_without_imputation.compile(optimizer='adam',loss='mse')

In [56]:
model_without_imputation.fit(x_train_initial_scaled,y_train_initial,epochs=100,batch_size=32,validation_data=(x_test_initial_scaled,
                                                                                                              y_test_initial))

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: nan - val_loss: nan
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: nan
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: nan - val_loss: nan
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: nan - val_loss: nan
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: nan - val_loss: nan
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: nan - val_loss: nan
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: nan - val_loss: nan
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: nan - val_loss: nan
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: nan - val_loss: nan
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: nan - val_loss: nan
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: nan - val_loss: nan
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: nan - val_loss: nan
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/

In [ ]:
#always handle missing values and perform feature scaling for neural network problems

In [57]:
from sklearn.impute import KNNImputer

In [58]:
imputer=KNNImputer()

In [59]:
x_imputed=imputer.fit_transform(x)

In [60]:
pd.DataFrame(x_imputed).isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [61]:
pd.DataFrame(x_imputed).head()

0     1     2    3      4      5     6       7    8      9     10      11    12
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3  396.90  4.98
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8  396.90  9.14
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8  392.83  4.03
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7  394.63  2.94
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7  396.90  7.56

In [62]:
x_train,x_testl,y_train,y_test=train_test_split(x_imputed,y,test_size=0.2,random_state=42)

In [63]:
print(x_train.shape)
print(x_testl.shape)
print(y_train.shape)
print(y_test.shape)

(404, 13)
(102, 13)
(404,)
(102,)


In [64]:
x_train_scaled=sc.fit_transform(x_train)

In [65]:
x_test_scaled=sc.transform(x_testl)

In [66]:
x_train_scaled

array([[ 1.25741615, -0.50062434,  1.03639503, ...,  0.84534281,
        -0.07433689,  1.76905748],
       [-0.34347617, -0.50062434, -0.41431747, ...,  1.20474139,
         0.4301838 , -0.56873109],
       [-0.40939005, -0.04888036, -0.7172775 , ..., -0.63717631,
         0.06529747, -0.65973989],
       ...,
       [-0.41157521,  2.94123457, -1.30717566, ..., -0.59225149,
         0.37901005, -0.92139019],
       [ 0.82783552, -0.50062434,  1.03639503, ...,  0.84534281,
        -2.69458597,  1.53584743],
       [-0.38780538, -0.50062434, -0.35314284, ...,  1.15981657,
        -3.12158061, -0.26157639]])

In [67]:
x_test_scaled

array([[-0.40303809, -0.50062434, -1.01004177, ..., -0.77195078,
         0.42887165, -0.48767637],
       [-0.40696803,  1.22030512, -0.66629865, ..., -0.32270256,
         0.44418004, -1.27120527],
       [-0.40148568, -0.50062434,  2.44049828, ...,  0.80041799,
         0.36993437,  0.79640092],
       ...,
       [ 1.14924812, -0.50062434,  1.03639503, ...,  0.84534281,
        -3.5124912 ,  1.24433486],
       [-0.40747512, -0.50062434, -0.94595407, ...,  0.08162084,
         0.43422959,  0.0555324 ],
       [-0.40266667, -0.50062434,  0.26879916, ...,  0.17147048,
         0.29470458, -0.5018965 ]])

In [68]:
model_with_imputation=Sequential()
model_with_imputation.add(Dense(32,activation='relu',input_dim=13))
model_with_imputation.add(Dense(16,activation='relu'))
model_with_imputation.add(Dense(1,activation='linear'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [69]:
model_with_imputation.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 32)                  │             448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 993 (3.88 KB)

 Trainable params: 993 (3.88 KB)

 Non-trainable params: 0 (0.00 B)

In [70]:
model_with_imputation.compile(optimizer='adam',loss='mse')

In [71]:
model_with_imputation.fit(x_train_scaled,y_train,epochs=100,batch_size=32,validation_data=(x_test_scaled,y_test))

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 571.6237 - val_loss: 497.3213
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 586.8375 - val_loss: 473.9226
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 533.5813 - val_loss: 446.8260
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 523.1287 - val_loss: 414.6098
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 481.7226 - val_loss: 375.5441
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 429.9691 - val_loss: 329.0895
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 372.7670 - val_loss: 275.0719
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 300.6755 - val_loss: 218.3461
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 264.2893 - val_loss: 163.8272
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 188.5509 - val_loss: 119.1665
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 158.5798 - val_loss: 87.5196
Epoch 12/100
13/13

In [72]:
model_with_imputation.fit(x_train_scaled,y_train,epochs=400,batch_size=32,validation_data=(x_test_scaled,y_test))

Epoch 1/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 9.5186 - val_loss: 11.6397
Epoch 2/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.6405 - val_loss: 11.5875
Epoch 3/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.5951 - val_loss: 11.5118
Epoch 4/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5302 - val_loss: 11.5627
Epoch 5/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6411 - val_loss: 11.4414
Epoch 6/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.9310 - val_loss: 11.4091
Epoch 7/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7229 - val_loss: 11.4464
Epoch 8/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.4810 - val_loss: 11.2819
Epoch 9/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.2064 - val_loss: 11.2994
Epoch 10/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 11.3050 - val_loss: 11.2644
Epoch 11/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 11.2003 - val_loss: 11.2836
Epoch 12/400
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1